#!/usr/bin/env python

from PIL import Image
from shaders import ComicShader
from os.path import isfile
from sys import stderr
from sys import exit

import argparse


argparser = argparse.ArgumentParser(description = 'Adds a comic book filter effect to an image.')
argparser.add_argument('infile', type = str)
argparser.add_argument('outfile', type = str, default = "", help = "Defaults the value of infile.")
argparser.add_argument('-c', '--color', default = True, dest = 'mono', action='store_false')


args = argparser.parse_args()
if args.outfile == "":
	args.outfile = args.infile

try:
	image = Image.open(args.infile)
except IOError as e:
	if not isfile(args.infile):
		stderr.writeln("No such file:  %s" % args.infile)

		exit(2)
	else:
		stderr.writeln(e.strerror)

		exit(2)

target = Image.new("RGBA", image.size, None)
target.paste(image)
shader.apply(target)
target.save(args.outfile)
