#!/usr/bin/env python

from PIL import Image
from shaders import ComicShader

import argparse

argparser = argparse.ArgumentParser(description = 'Add a comic book filter effect to an image.')
argparser.add_argument('target', type = str, help = "Path comic book effect should be applied to.")
argparser.add_argument('-o', '--out', type = str, default = None, help = "Path rendered image should be written to.  Defaults to value of 'in' argument if not given.")
argparser.add_argument('-s', '--scale', type = int, default = 1)
argparser.add_argument('-c', '--color', default = False, dest = 'color', action='store_true')

args = argparser.parse_args()
if args.out == None:
	args.out = args.target


input_image = Image.open(args.target)

image = Image.new("RGBA", input_image.size, (0, 0, 0, 1))
image.paste(input_image)
for filter in [ComicShader(args.scale, args.color)]:
	filter(image)
image.save(args.out)
